version: "3.9"

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"
networks:
  laravel:

volumes:
  dbdata: