version: "3.9"
name: app
services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www
      - /var/www/vendor

  db:
    image: mysql:8.3
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app

  queue:
    build: .
    container_name: queue
    command: php artisan queue:work --tries=3 --timeout=90
    networks:
      - app
    volumes:
      - .:/var/www
    depends_on:
      - db
networks:
  app:

volumes:
  dbdata: